server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;  # ← moved here

    location / {
        index index.html;
        try_files $uri /index.html;
    }

    location = /index.html {
        add_header Cache-Control "no-cache, no-store, must-revalidate";
        add_header Pragma "no-cache";
        add_header Expires "0";
    }

    location /assets/ {
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /api/ {
        proxy_pass http://backend:5000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /socket.io {
        proxy_http_version 1.1;
        proxy_buffering off; # added this
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host; # added this
        proxy_pass http://backend:5000/socket.io;
        proxy_read_timeout 86400; # added this
    }
}