services:
  backend:
    build: ./backend
    container_name: poker-backend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://pokeruser:pokerpass@db:5432/pokerdb
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: poker-frontend
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes: # PRODUCTION ONLY
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - /etc/ssl/poker:/etc/ssl/poker:ro  # Mount certs from host into container (read-only)

  db:
    image: postgres
    container_name: poker-postgres
    restart: always
    environment:
      POSTGRES_USER: pokeruser
      POSTGRES_PASSWORD: pokerpass
      POSTGRES_DB: pokerdb
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: poker-redis
    ports: []  # No port exposure
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]

volumes:
  pgdata:
