services:
  backend:
    image: ghcr.io/soljt/poker-backend:latest
    container_name: poker-backend
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://pokeruser:${POSTGRES_PASSWORD}@db:5432/pokerdb
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - CACHE_REDIS_HOST=redis
      - CACHE_REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - POKER_BOT_PASSWORD=${POKER_BOT_PASSWORD}
    # no volume needed for hot reload (on prod)
    networks:
      - web
      - backend_net

  frontend:
    image: ghcr.io/soljt/poker-frontend:latest
    container_name: poker-frontend
    # moving to global reverse proxy for VM
    # ports:
    #   - "80:80"
    #   - "443:443"
    depends_on:
      - backend
    # no volumes; the nginx conf should be baked into the image
    networks:
      - web
      - backend_net

  db:
    image: postgres
    container_name: poker-postgres
    restart: always
    environment:
      POSTGRES_USER: pokeruser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pokerdb
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - backend_net

  redis:
    image: redis:alpine
    container_name: poker-redis
    ports: []  # No port exposure
    restart: always
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf:ro
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - backend_net

networks:
  web:
    external: true
  
  backend_net:
    driver: bridge